In [21]:
import numpy as np

In [6]:
mylist = [1,2,3,4,5]
type(np.array(mylist)) 

numpy.ndarray

In [8]:
arr = np.array(mylist)
arr

array([1, 2, 3, 4, 5])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
np.ones((10,15),dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [30]:
np.random.randint(0,10)

3

In [33]:
np.random.randint(0,1000,(15,10))

array([[508, 955, 367, 784, 879,   2, 162, 830, 754, 820],
       [672, 572, 465, 807, 744, 518, 692, 666, 726, 792],
       [  7, 480, 825, 190, 485, 906, 771, 185, 274, 697],
       [439, 333, 134, 258,  80,  85, 607, 316, 232, 664],
       [581, 251, 298, 852, 693, 100, 163, 999, 757,  34],
       [630, 315, 102, 354, 305, 972,  36, 187, 556, 145],
       [154, 209, 768, 338, 932, 392, 189, 546, 209, 102],
       [399, 564, 529, 275, 266, 907, 133,  62, 861, 602],
       [758, 490, 378, 179, 393, 835, 770, 930, 547, 361],
       [ 61, 490, 299,  91, 568,  52,  23, 692, 112, 759],
       [111, 347,  71, 367, 164, 765, 763, 867, 513, 387],
       [571, 825, 423, 895, 373, 263, 287, 751, 278,  75],
       [838, 937,  32, 335, 732, 188, 726, 859,  66, 727],
       [510, 462, 517, 733, 340, 841, 705, 154, 933, 997],
       [538, 774,  54, 446, 186, 329, 244, 392, 256, 169]])

In [51]:
# for fixed value in random.randint method
np.random.seed(101)
arr = np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [38]:
arr.max()

95

In [39]:
arr.min()

9

In [40]:
arr.mean()

60.8

In [41]:
arr.argmax() # return the max position index

0

In [42]:
arr.argmin() # retuen the min position index

7

In [55]:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [57]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [58]:
mat[3,3]

33

In [59]:
mat[0,:] # determine rows

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
mat[:,0] # determine cols

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [65]:
a = np.array([[1,2,3],[4,5,6]])
a.sum()

21

In [66]:
a.sum(axis = 0) # axis = 0 provide to be add in matrix rows side oe col side

array([5, 7, 9])

In [67]:
a.sum(axis = 1)

array([ 6, 15])

In [72]:
b = np.array([[7,8,9],[2,8,0]])
a.dot(b.transpose())

array([[ 50,  18],
       [122,  48]])

In [73]:
len(dir(np))

622

In [74]:
np.cross(a,b)

array([[ -6,  12,  -6],
       [-48,  12,  22]])

In [75]:
a = np.array([[11,2,3],[4,5,6]])
np.sort(a, axis = 0)

array([[ 4,  2,  3],
       [11,  5,  6]])

In [76]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [77]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [79]:
c = a-b
c

array([20, 29, 38, 47])

In [80]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [81]:
a**2

array([ 400,  900, 1600, 2500], dtype=int32)

In [82]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [83]:
a < 35

array([ True,  True, False, False])

In [84]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
A * B # element wise product

array([[2, 0],
       [0, 4]])

In [85]:
A @ B # matrix product

array([[5, 4],
       [3, 4]])

In [86]:
A.dot(B) # another matrix product

array([[5, 4],
       [3, 4]])